# Generated by Django 5.1.2 on 2024-11-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('mID', models.CharField(default='', max_length=10)),
                ('Phone number', models.CharField(default='', max_length=10)),
                ('Photo', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('studentID', models.CharField(error_messages={'unique': 'A user with that ID already exists.'}, max_length=10, unique=True)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('fatherNumber', models.CharField(max_length=10)),
                ('profilePic', models.ImageField(upload_to='assets/images')),
                ('grade', models.IntegerField(default=8)),
            ],
        ),
    ]
