# Generated by Django 5.1.2 on 2024-11-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parent_rename_fathernumber_student_parentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=8, max_length=12),
        ),
    ]
