# Generated by Django 5.1.2 on 2024-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_completedassignment_student'),
        ('users', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignments_completed',
            field=models.ManyToManyField(related_name='students', through='assignments.CompletedAssignment', to='assignments.assignment'),
        ),
    ]
