# Generated by Django 5.1.2 on 2024-11-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('users', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
