# Generated by Django 5.1.2 on 2024-11-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_completedassignment_student_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedassignment',
            name='student',
        ),
    ]
