# Generated by Django 5.1.2 on 2024-11-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_completedassignment_student'),
        ('users', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedassignment',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
